"""add timetable and update examination

Revision ID: 21dc6d2d4d0a
Revises: 54d7beefc1a7
Create Date: 2026-09-25 09:52:46.150472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21dc6d2d4d0a'
down_revision = '54d7beefc1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examination_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id', 'subject_id', name='uq_examination_subject_timetable')
    )
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('session_config', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('excluded_dates', sa.JSON(), nullable=False))
        batch_op.drop_constraint(batch_op.f('examinations_subject_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.drop_column('exam_date')
        batch_op.drop_column('session')
        batch_op.drop_column('start_time')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('session', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('exam_date', sa.DATE(), autoincrement=False, nullable=False))
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('examinations_subject_id_fkey'), 'subjects', ['subject_id'], ['id'])
        batch_op.drop_column('excluded_dates')
        batch_op.drop_column('session_config')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('semester')
        batch_op.drop_column('course_id')
        batch_op.drop_column('name')

    op.drop_table('timetables')
    # ### end Alembic commands ###
