"""add exam fee status to registrations

Revision ID: fc35b85d78a3
Revises: 21dc6d2d4d0a
Create Date: 2026-09-29 16:03:51.690549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc35b85d78a3'
down_revision = '21dc6d2d4d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_registrations', schema=None) as batch_op:
        batch_op.drop_column('fee_status')

    # ### end Alembic commands ###
